
default: &default
  adapter: postgresql
  encoding: unicode
  pool: <%= ENV.fetch("RAILS_MAX_THREADS") { 5 } %>


development:
  primary:
    database: help_search_development
    adapter: postgresql
  searches:
    database: h_s_search
    adapter: postgresql
    migrations_paths: db/searches_migrate
  searches_replica:
    database: h_s_search_replica
    adapter: postgresql
    replica: true

test:
  primary:
    database: help_search_development_test
    adapter: postgresql
  searches:
    database: h_s_search_test
    adapter: postgresql
    migrations_paths: db/searches_migrate
  searches_replica:
    database: h_s_search_replica_test
    adapter: postgresql
    replica: true
    

production:
  <<: *default
  database: help_search_production
  username: help_search
  password: <%= ENV["HELP_SEARCH_DATABASE_PASSWORD"] %>
