
default: &default
  adapter: postgresql
  encoding: unicode
  pool: <%= ENV.fetch("RAILS_MAX_THREADS") { 5 } %>


development:
  primary:
    database: help_search_development
    adapter: postgresql
  searches:
    database: h_s_search
    adapter: postgresql
    migrations_paths: db/searches_migrate
  searches_replica:
    database: h_s_search_replica
    adapter: postgresql
    replica: true

test:
  primary:
    database: help_search_development_test
    adapter: postgresql
  searches:
    database: h_s_search_test
    adapter: postgresql
    migrations_paths: db/searches_migrate
  searches_replica:
    database: h_s_search_replica_test
    adapter: postgresql
    replica: true
    

production:
  primary: 
    adapter: postgresql
  searches:
    <<: *default
    migrations_paths: db/searches_migrate
    url: <%= ENV["HEROKU_POSTGRESQL_PUCE"] %>
  searches_replica:
    <<: *default
    url: <%= ENV["HEROKU_POSTGRESQL_IVORY"] %>
    replica: true


# postgres://ibgvohtrkzcoxc:e5aefe45e590facb52d6661c86c29d9d697d96c390de7889c837599f6eca0e4a@ec2-54-158-26-89.compute-1.amazonaws.com:5432/d67rgd9hiojubvd67rgd9hiojubv